# --- General options --- #

environment : crib  # base, crib, mirror
behavior : self_touch   # self_touch, hand_rehard, mirror
actuation_model : spring_damper  # spring_damper, muscle, positional
max_episode_steps : 1000

# --- Rendering options --- #
render_width : 480
render_height : 480


# --- Sensory modalities --- #

# Proprioception
proprio_velocity : True
proprio_torque : True
proprio_limits : True
proprio_actuation : True

# Vestibular
vestibular_active : True

# Vision
vision_active : True
vision_resolution : 64

# Touch
touch_active : True
touch_scale : 1.0
touch_function : force_vector
touch_response_function : spread_linear
touch_left_toes : True
touch_right_toes : True
touch_left_foot : True
touch_right_foot : True
touch_left_lower_leg : True
touch_right_lower_leg : True
touch_left_upper_leg : True
touch_right_upper_leg : True
touch_hip : True
touch_lower_body : True
touch_upper_body : True
touch_head : True
touch_left_eye : True
touch_right_eye : True
touch_left_upper_arm : True
touch_right_upper_arm : True
touch_left_lower_arm : True
touch_right_lower_arm : True
touch_left_hand : True
touch_right_hand : True
touch_left_fingers : True
touch_right_fingers : True


# --- Motor modalities --- #

# Lock body parts

