# Configuration file for running BabyBench experiments.
# See wiki for details: https://babybench.github.io/2025/wiki

# --- General options --- #

save_dir : results/self_touch
behavior : self_touch   # options: self_touch, hand_regard, mirror

# --- Experiment parameters --- #

max_episode_steps : 1000
frame_skip : 1
render_size : 480
save_logs_every: 100

# --- Sensory modalities --- #

# Proprioception
proprio_velocity : True
proprio_torque : True
proprio_limits : True
proprio_actuation : True

# Vestibular
vestibular_active : True

# Vision
vision_active : False
vision_resolution : 64

# Touch
touch_active : False
touch_scale : 1.
touch_function : force_vector
touch_response : spread_linear
touch_hands : True
touch_arms : True
touch_feet : True
touch_legs : True
touch_body : True
touch_head : True
touch_eyes : False

# --- Motor modalities --- #

actuation_model : spring_damper  # options: spring_damper, muscle, positional

# Actuated body parts (Some joints may be locked, see descriptions in wiki)
act_hands : True
act_arms : True
act_feet : True
act_legs : True
act_body : True
act_head : True
act_eyes : True