# --- General options --- #

environment : crib # plain, crib, cubes
actuation_model : spring_damper  # spring_damper, muscle, positional
max_episode_steps : 1000

# --- BabyBench behaviors --- #

self_touch : True
hand_regard : False
mirror : False

# --- Sensory modalities --- #

# Proprioception
proprio_velocity : True
proprio_torque : True
proprio_limits : True
proprio_actuation : True

# Vestibular
vestibular : True

# Vision
vision_resolution : 64

# Touch
touch_scale : 1.0
touch_function : force_vector
touch_response_function : spread_linear
touch_left_toes : True
touch_right_toes : True
touch_left_foot : True
touch_right_foot : True
touch_left_lower_leg : True
touch_right_lower_leg : True
touch_left_upper_leg : True
touch_right_upper_leg : True
touch_hip : True
touch_lower_body : True
touch_upper_body : True
touch_head : True
touch_left_eye : True
touch_right_eye : True
touch_left_upper_arm : True
touch_right_upper_arm : True
touch_left_lower_arm : True
touch_right_lower_arm : True
touch_left_hand : True
touch_right_hand : True
touch_left_fingers : True
touch_right_fingers : True


# --- Motor modalities --- #

# Lock joints
