# Configuration file for running BabyBench environments. See wiki for details:
# https://babybench.github.io/babybench2025/wiki/about/environments/

# --- General options --- #

save_dir : results/hand_regard
behavior : hand_regard   # options: self_touch, hand_regard, mirror

# --- Experiment parameters --- #

max_episode_steps : 1000
frame_skip : 1
render_size : 480
save_logs_every: 100

# --- Sensory modalities --- #

# Proprioception
proprio_velocity : True
proprio_torque : True
proprio_limits : True
proprio_actuation : True

# Vestibular
vestibular_active : True

# Vision
vision_active : True
vision_resolution : 64

# Touch
touch_active : False
touch_scale : 10.
touch_function : force_vector
touch_response : spread_linear
touch_hands : True
touch_fingers : True
touch_arms : True
touch_feet : True
touch_legs : True
touch_body : True
touch_head : True
touch_eyes : False

# --- Motor modalities --- #

# Actuation model
actuation_model : spring_damper  # options: spring_damper, muscle, positional

# Lock joints
lock_hands : False
lock_fingers : True
lock_arms : False
lock_feet : False
lock_legs : False
lock_body : False
lock_head : False
lock_eyes : False